from __future__ import annotations

import re

ORIGINAL_DDS_ROOT = ""
PNG_ROOT = ""
TEXTURE_EDITOR_PNG_ROOT = ""
OUTPUT_ROOT = ""
TEXCONV_PATH = ""

DRY_RUN = False
LOG_CSV = ""
ALLOW_UNIQUE_BASENAME_FALLBACK = True

OVERWRITE_EXISTING_DDS = True
INCLUDE_FILTERS = ""
ENABLE_CHAINNER = False
CHAINNER_EXE_PATH = ""
CHAINNER_CHAIN_PATH = ""
CHAINNER_OVERRIDE_JSON = ""
UPSCALE_BACKEND_NONE = "none"
UPSCALE_BACKEND_CHAINNER = "chainner"
UPSCALE_BACKEND_REALESRGAN_NCNN = "realesrgan_ncnn"
DEFAULT_UPSCALE_BACKEND = UPSCALE_BACKEND_CHAINNER if ENABLE_CHAINNER else UPSCALE_BACKEND_NONE
UPSCALE_POST_CORRECTION_NONE = "none"
UPSCALE_POST_CORRECTION_MATCH_MEAN_LUMA = "match_mean_luma"
UPSCALE_POST_CORRECTION_MATCH_LEVELS = "match_levels"
UPSCALE_POST_CORRECTION_MATCH_HISTOGRAM = "match_histogram"
UPSCALE_POST_CORRECTION_SOURCE_MATCH_BALANCED = "source_match_balanced"
UPSCALE_POST_CORRECTION_SOURCE_MATCH_EXTENDED = "source_match_extended"
UPSCALE_POST_CORRECTION_SOURCE_MATCH_EXPERIMENTAL = "source_match_experimental"
DEFAULT_UPSCALE_POST_CORRECTION = UPSCALE_POST_CORRECTION_SOURCE_MATCH_BALANCED
REALESRGAN_NCNN_EXE_PATH = ""
REALESRGAN_NCNN_MODEL_DIR = ""
REALESRGAN_NCNN_MODEL_NAME = ""
REALESRGAN_NCNN_SCALE = 4
REALESRGAN_NCNN_TILE_SIZE = 0
REALESRGAN_NCNN_EXTRA_ARGS = ""
ENABLE_AUTOMATIC_TEXTURE_RULES = True
ENABLE_UNSAFE_TECHNICAL_OVERRIDE = False
RETRY_SMALLER_TILE_ON_FAILURE = True
ENABLE_MOD_READY_LOOSE_EXPORT = False
MOD_READY_EXPORT_ROOT = ""
MOD_READY_EXPORT_DIRNAME = "mod_ready_loose_export"
MOD_READY_CREATE_NO_ENCRYPT = True
MOD_READY_PACKAGE_TITLE = "Crimson Forge Toolkit Mod"
MOD_READY_PACKAGE_VERSION = "1.0"
MOD_READY_PACKAGE_AUTHOR = ""
MOD_READY_PACKAGE_DESCRIPTION = ""
MOD_READY_PACKAGE_NEXUS_URL = ""
UPSCALE_TEXTURE_PRESET_BALANCED = "balanced"
UPSCALE_TEXTURE_PRESET_COLOR_UI = "color_ui"
UPSCALE_TEXTURE_PRESET_COLOR_UI_EMISSIVE = "color_ui_emissive"
UPSCALE_TEXTURE_PRESET_ALL = "all"
DEFAULT_UPSCALE_TEXTURE_PRESET = UPSCALE_TEXTURE_PRESET_BALANCED

DDS_FORMAT_MODE_MATCH_ORIGINAL = "match_original"
DDS_FORMAT_MODE_CUSTOM = "custom"
DDS_SIZE_MODE_PNG = "png"
DDS_SIZE_MODE_ORIGINAL = "original"
DDS_SIZE_MODE_CUSTOM = "custom"
DDS_MIP_MODE_MATCH_ORIGINAL = "match_original"
DDS_MIP_MODE_FULL_CHAIN = "full_chain"
DDS_MIP_MODE_SINGLE = "single"
DDS_MIP_MODE_CUSTOM = "custom"

DEFAULT_DDS_FORMAT_MODE = DDS_FORMAT_MODE_MATCH_ORIGINAL
DEFAULT_DDS_CUSTOM_FORMAT = "BC7_UNORM"
DEFAULT_DDS_SIZE_MODE = DDS_SIZE_MODE_PNG
DEFAULT_DDS_CUSTOM_WIDTH = 2048
DEFAULT_DDS_CUSTOM_HEIGHT = 2048
DEFAULT_DDS_MIP_MODE = DDS_MIP_MODE_MATCH_ORIGINAL
DEFAULT_DDS_CUSTOM_MIP_COUNT = 1
ENABLE_DDS_STAGING = False
DDS_STAGING_ROOT = ""
ENABLE_INCREMENTAL_RESUME = False
TEXTURE_RULES_TEXT = ""
ARCHIVE_PACKAGE_ROOT = ""
ARCHIVE_EXTRACT_ROOT = ""
ARCHIVE_FILTER_TEXT = ""
ARCHIVE_EXCLUDE_FILTER_TEXT = ""
ARCHIVE_EXTENSION_FILTER = ".dds"
ARCHIVE_PACKAGE_FILTER_TEXT = ""
ARCHIVE_STRUCTURE_FILTER = ""
ARCHIVE_ROLE_FILTER = "all"
ARCHIVE_EXCLUDE_COMMON_TECHNICAL_SUFFIXES = False
ARCHIVE_MIN_SIZE_KB = 0
ARCHIVE_PREVIEWABLE_ONLY = False
ARCHIVE_SCAN_CACHE_DIRNAME = "archive_cache"
ARCHIVE_IMAGE_EXTENSIONS = {
    ".bmp",
    ".dds",
    ".gif",
    ".hdr",
    ".jpeg",
    ".jpg",
    ".png",
    ".tga",
    ".tif",
    ".tiff",
    ".webp",
}
ARCHIVE_TEXT_EXTENSIONS = {
    ".cfg",
    ".csv",
    ".dae",
    ".gltf",
    ".h",
    ".hpp",
    ".ini",
    ".json",
    ".log",
    ".lua",
    ".material",
    ".mtl",
    ".obj",
    ".shader",
    ".txt",
    ".xml",
    ".yaml",
    ".yml",
}
ARCHIVE_MODEL_EXTENSIONS = {
    ".3ds",
    ".dae",
    ".fbx",
    ".glb",
    ".gltf",
    ".mesh",
    ".mdl",
    ".model",
    ".obj",
    ".pac",
    ".pam",
    ".pat",
    ".patx",
}
ARCHIVE_TEXT_PREVIEW_LIMIT = 240_000
ARCHIVE_BINARY_HEX_PREVIEW_LIMIT = 256

APP_ORGANIZATION = "Ratrider"
APP_NAME = "CrimsonForgeToolkit"
APP_TITLE = "Crimson Forge Toolkit"
LEGACY_APP_NAMES = ("CrimsonTextureForge", "DDSRebuildApp")
APP_VERSION = "0.6.5"
CRIMSON_DESERT_STEAM_APP_ID = "3321460"
DEFAULT_UI_THEME = "graphite"
DEFAULT_UI_FONT_FAMILY = "Segoe UI"
DEFAULT_UI_FONT_SIZE = 10
DEFAULT_UI_DATA_FONT_SIZE = 10
UI_FONT_SIZE_MIN = 8
UI_FONT_SIZE_MAX = 15
DEFAULT_UI_DENSITY = "compact"
DEFAULT_UI_LOG_FONT_FAMILY = "Consolas"
DEFAULT_UI_LOG_FONT_SIZE = 8
DEFAULT_UI_LOG_FONT_BOLD = False
UI_FONT_FAMILY_OPTIONS = (
    "Segoe UI",
    "Aptos",
    "Calibri",
    "Verdana",
    "Tahoma",
)
LOG_FONT_FAMILY_OPTIONS = (
    "Consolas",
    "Cascadia Mono",
    "Cascadia Code",
    "Lucida Console",
    "Courier New",
)
CHAINNER_SETTLE_SECONDS = 2.0
CHAINNER_ENV_VARS_TO_REMOVE = ("ELECTRON_RUN_AS_NODE",)
CHAINNER_PROGRESS_RE = re.compile(r"Executed\s+(\d+)\s*/\s*(\d+)\s+nodes", re.IGNORECASE)
CHAINNER_NO_VALID_IMAGES_RE = re.compile(
    r"(?P<directory>[A-Za-z]:[\\/][^\r\n]+?)\s+has\s+no\s+valid\s+images",
    re.IGNORECASE,
)
SUPPORTED_CHAINNER_LOAD_IMAGE_SUFFIXES = {
    ".bmp",
    ".dds",
    ".exr",
    ".gif",
    ".hdr",
    ".jpeg",
    ".jpg",
    ".jp2",
    ".j2k",
    ".png",
    ".tga",
    ".tif",
    ".tiff",
    ".webp",
}
CHAINNER_DOWNLOAD_PAGE_URL = "https://chainner.app/download/"
DIRECTXTEX_RELEASES_PAGE_URL = "https://github.com/microsoft/DirectXTex/releases"
REALESRGAN_NCNN_RELEASES_PAGE_URL = "https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan/releases"

DDS_MAGIC = b"DDS "
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

DDPF_ALPHAPIXELS = 0x1
DDPF_ALPHA = 0x2
DDPF_FOURCC = 0x4
DDPF_RGB = 0x40
DDPF_LUMINANCE = 0x20000

DXGI_TO_TEXCONV = {
    28: "R8G8B8A8_UNORM",
    29: "R8G8B8A8_UNORM_SRGB",
    71: "BC1_UNORM",
    72: "BC1_UNORM_SRGB",
    74: "BC2_UNORM",
    75: "BC2_UNORM_SRGB",
    77: "BC3_UNORM",
    78: "BC3_UNORM_SRGB",
    80: "BC4_UNORM",
    81: "BC4_SNORM",
    83: "BC5_UNORM",
    84: "BC5_SNORM",
    87: "B8G8R8A8_UNORM",
    91: "B8G8R8A8_UNORM_SRGB",
    95: "BC6H_UF16",
    96: "BC6H_SF16",
    98: "BC7_UNORM",
    99: "BC7_UNORM_SRGB",
}

LEGACY_FOURCC_TO_TEXCONV = {
    b"DXT1": "BC1_UNORM",
    b"DXT3": "BC2_UNORM",
    b"DXT5": "BC3_UNORM",
    b"ATI1": "BC4_UNORM",
    b"BC4U": "BC4_UNORM",
    b"BC4S": "BC4_SNORM",
    b"ATI2": "BC5_UNORM",
    b"BC5U": "BC5_UNORM",
    b"BC5S": "BC5_SNORM",
}

LEGACY_NUMERIC_FOURCC_TO_TEXCONV = {
    # Legacy D3D numeric FOURCC values observed in Crimson Desert effect/vector DDS files.
    113: "R16G16B16A16_FLOAT",
    116: "R32G32B32A32_FLOAT",
}

SUPPORTED_TEXCONV_FORMAT_CHOICES = (
    "R16_FLOAT",
    "R16G16_FLOAT",
    "R16G16B16A16_FLOAT",
    "R16G16B16A16_SNORM",
    "R32_FLOAT",
    "R32G32_FLOAT",
    "R32G32B32A32_FLOAT",
    "R8G8B8A8_UNORM",
    "R8G8B8A8_UNORM_SRGB",
    "B8G8R8A8_UNORM",
    "B8G8R8A8_UNORM_SRGB",
    "B8G8R8X8_UNORM",
    "BC1_UNORM",
    "BC1_UNORM_SRGB",
    "BC2_UNORM",
    "BC2_UNORM_SRGB",
    "BC3_UNORM",
    "BC3_UNORM_SRGB",
    "BC4_UNORM",
    "BC4_SNORM",
    "BC5_UNORM",
    "BC5_SNORM",
    "BC6H_UF16",
    "BC6H_SF16",
    "BC7_UNORM",
    "BC7_UNORM_SRGB",
)
